
project_id = "epwggtbgdtaxietedjcn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[db.migrations]]
migrations_dir = "supabase/migrations"

[functions.reset-expired-discounts]
verify_jwt = true
