
project_id = "epwggtbgdtaxietedjcn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[auth.sms]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

# Configure the edge functions
[functions]
enabled = true
port = 54325

# Configure the PayPal webhook to be public
[functions.verify-paypal-webhook]
verify_jwt = false
