
project_id = "epwggtbgdtaxietedjcn"

[functions.process-taphoammo-order]
verify_jwt = true

[functions.mock-taphoammo]
verify_jwt = true

[functions.purchase-product]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.sync-taphoammo]
verify_jwt = true

[functions.sync-taphoammo-api]
verify_jwt = true

[functions.sync-taphoammo-products]
verify_jwt = true

[functions.taphoammo-api]
verify_jwt = true

[functions.process-paypal-deposit]
verify_jwt = true

[functions.verify-paypal-webhook]
verify_jwt = false

[functions.verify-usdt-transaction]
verify_jwt = true
