
# This is your Supabase project's configuration file

project_id = "epwggtbgdtaxietedjcn"

# Apply migrations when pushing
migrations.migrate_on_push = true

[api]
# Port to use for the API URL.
port = 54321
# Enable JWT verification for all API requests.
# If false, it will still be enforced for all protected endpoints.
verify_jwt = true

[db]
# Port to use for the database.
port = 54322
# The database major version to use. This has to be the same as your remote database's.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server
[inbucket]
# Port to use for the email testing server web interface.
port = 54324

[storage]
# The maximum file size allowed (in bytes).
file_size_limit = 5242880

[auth]
# The base URL of your website. Used as an allow-list for redirects (no trailing slash).
site_url = "http://localhost:3000"
# List of additional redirect URLs that users can sign in from (no trailing slash, leave empty for no additional URLs).
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Use an external OAuth provider. The full list of providers are: "apple", "azure", "bitbucket",
# "discord", "facebook", "github", "gitlab", "google", "keycloak", "linkedin", "notion",
# "twitch", "twitter", "slack", "spotify", "workos", "zoom".
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[functions]
# Relative path to look for functions (in format ./{file}) from project root.
dir = "./supabase/functions"
[functions.calculate-loyalty-discount]
verify_jwt = true
[functions.award-loyalty-points]
verify_jwt = true
[functions.check-user-tier]
verify_jwt = true
