
# This is the default configuration file for a Supabase project

# Note: The project_id setting is not used in local development but is required by Supabase
project_id = "epwggtbgdtaxietedjcn"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://example.com"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
port = 54328
serve_port = 54329

[functions.sync-products]
verify_jwt = true

[functions.purchase-product]
verify_jwt = true

[functions.get-order-products]
verify_jwt = true
