// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epwggtbgdtaxietedjcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwd2dndGJnZHRheGlldGVkamNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTUxNDEsImV4cCI6MjA2MTA3MTE0MX0.1RAAgtMclmKaFF6nCgkZ2Pll6PZCMgeSuCHbIftrP7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);